### ISSUE TITLE
mapol leafes suck as fuck

### ISSUE THREAD

**Issue by mdoubleehhhhh** [brahseal/hackeybot#3]

**Comment by mdoubleehhhhh** [comment]
pls, this issue is not solved, no more closing of issues that are not solved, THANK YOU AVS

**Comment by mdoubleehhhhh** [comment]
i see no work on this, pls, didnt you say they are good? i dont even see a good dman in dat crappenheimers club

**Comment by brahseal** [comment]
SOLVED.

The leafs are good now
